-- 코드를 입력하세요
SELECT B.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME
FROM ANIMAL_OUTS AS B
JOIN ANIMAL_INS AS A ON B.ANIMAL_ID = A.ANIMAL_ID
WHERE (B.SEX_UPON_OUTCOME LIKE 'Spayed%' OR B.SEX_UPON_OUTCOME LIKE 'Neutered%')
    AND
      (A.SEX_UPON_INTAKE LIKE 'Intact%')
ORDER BY B.ANIMAL_ID;