-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT(U.USER_ID)) AS USERS
FROM USER_INFO U
JOIN ONLINE_SALE S
ON U.USER_ID = S.USER_ID
WHERE U.USER_ID IN (SELECT USER_ID
                    FROM ONLINE_SALE
                    GROUP BY USER_ID
                    HAVING COUNT(*) >= 1)
GROUP BY YEAR, MONTH, GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER