-- 코드를 입력하세요
SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_OUTS AS B
LEFT JOIN ANIMAL_INS AS A ON B.ANIMAL_ID = A.ANIMAL_ID
WHERE B.ANIMAL_ID NOT IN (SELECT ANIMAL_ID
                          FROM ANIMAL_INS)
ORDER BY B.ANIMAL_ID;