-- 코드를 입력하세요
# SELECT SUM(FIRST_HALF.TOTAL_ORDER+JULY.TOTAL_ORDER) AS SUM
# FROM FIRST_HALF
# JOIN JULY ON FIRST_HALF.FLAVOR = JULY.FLAVOR
# GROUP BY FIRST_HALF.FLAVOR
# ORDER BY SUM DESC
# LIMIT 3;

SELECT A.FLAVOR
FROM FIRST_HALF AS A
JOIN JULY AS B ON A.FLAVOR = B.FLAVOR
GROUP BY FLAVOR
ORDER BY SUM(A.TOTAL_ORDER+B.TOTAL_ORDER) DESC
LIMIT 3;