-- 코드를 입력하세요
SELECT DISTINCT(R.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R
JOIN CAR_RENTAL_COMPANY_CAR C
ON R.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '세단' AND MONTH(R.START_DATE) = 10
ORDER BY R.CAR_ID DESC