SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE F
JOIN USED_GOODS_BOARD B ON B.BOARD_ID = F.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(C.VIEWS) FROM USED_GOODS_BOARD C)
ORDER BY FILE_ID DESC;